#!/bin/bash

# Skrip untuk menampilkan daftar user Shadowsocks dari config.json

echo "==================================="
echo "   DAFTAR PENGGUNA SHADOWSOCKS"
echo "==================================="
echo "Username           | Exp. Date"
echo "-----------------------------------"

# Menggunakan grep untuk mencari penanda user SS (#!#)
grep -E "^#!# " "/etc/xray/config.json" | cut -d ' ' -f 2,3 | column -t | sort | uniq

if [ $? -ne 0 ] || [ $(grep -c -E "^#!# " "/etc/xray/config.json") -eq 0 ]; then
    echo "Tidak ada pengguna Shadowsocks yang ditemukan."
fi

echo "==================================="
